name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: book_management_testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pgsql, pdo_pgsql, bcmath, exif, gd

      - name: Copy .env
        run: |
          cd backend
          cp .env.example .env.testing
          sed -i 's/DB_HOST=pgsql/DB_HOST=localhost/g' .env.testing
          sed -i 's/DB_USERNAME=sail/DB_USERNAME=postgres/g' .env.testing
          sed -i 's/DB_PASSWORD=password/DB_PASSWORD=postgres/g' .env.testing
          sed -i 's/DB_DATABASE=book_management/DB_DATABASE=book_management_testing/g' .env.testing

      - name: Install Dependencies
        run: |
          cd backend
          composer install --prefer-dist --no-interaction --no-progress

      - name: Generate App Key
        run: |
          cd backend
          php artisan key:generate --env=testing

      - name: Generate JWT Secret
        run: |
          cd backend
          php artisan jwt:secret --force --env=testing

      - name: Run Migrations
        run: |
          cd backend
          php artisan migrate --env=testing

      - name: PHPUnit Tests
        run: |
          cd backend
          php artisan test --env=testing

      - name: Static Analysis
        run: |
          cd backend
          composer analyze

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Install Dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          cd frontend
          yarn lint

      - name: Run Unit Tests
        run: |
          cd frontend
          yarn test

      - name: Build Check
        run: |
          cd frontend
          yarn build
        env:
          BROWSER_API_BASE_URL: 'http://localhost:8000/api'
          SERVER_API_BASE_URL: 'http://laravel.test/api'

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring

      - name: Install Dependencies
        run: |
          cd backend
          composer install --prefer-dist --no-interaction --no-progress

      - name: Run Security Check
        run: |
          cd backend
          composer audit
